### ISSUE TITLE
另一种发声方式

### ISSUE THREAD

**Issue by qnnnnez** [XiaofengdiZhu/SSS#2]
把所有音频放在一个音频文件里，发声时 seek 到对应的时间点
好处：
- 无延迟
- 减少音频文件数量，提高速度

[Edit]
修正 Markdown 格式

**Comment by brendan-lee** [comment]
恐怕每次发声还是会重新读取？

**Comment by brendan-lee** [comment]
啊我明白你的意思了= =

**Comment by qnnnnez** [comment]
看起来已改进
关闭了
